name: Lethos
options:
  bundleIdPrefix: com.lethos
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: Lethos/Info.plist
    DEVELOPMENT_TEAM: ""

targets:
  Lethos:
    type: application
    platform: iOS
    sources:
      - path: Lethos
        excludes:
          - "Info.plist"
      - path: Lethos/Fonts
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lethos.app
        INFOPLIST_FILE: Lethos/Info.plist
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
